# Generated by Django 4.1.6 on 2023-04-19 06:14

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_applicant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.CharField(max_length=13, unique=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
