# Generated by Django 3.0.5 on 2023-04-25 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20230425_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='email',
            new_name='user',
        ),
    ]
